### PR TITLE
Fix broken ping in default error message

### PR DESCRIPTION
**Pull request by suprstarrd**
This adds a space in the `ERROR_DEFAULT` issue comment, resolving https://github.com/rossjrw/rossjrw/pull/1274#issuecomment-952947203

### CODE REVIEW

**Comment by rossjrw** [comment]
If possible, I'd much prefer to have these two features in their own PRs

**Comment by suprstarrd** [comment]
Got it 👍

**Review by rossjrw — APPROVED** [review]

**Comment by rossjrw** [comment]
Thank you!

**Comment by suprstarrd** [comment]
🎉 Good title change. You're welcome!

**Pull request merged**
